Refactor some utility scripts

diff --git a/tools/bin/50x b/tools/bin/50x
--- a/tools/bin/50x
+++ b/tools/bin/50x
@@ -35,7 +35,10 @@ then
     )
 fi
 
-php "${libexec}/50x.php" > "${public}/50x.html" || (
-    echo "Unable to create a 50x.html" >&2;
-    exit 1;
-)
+# Create a 50x.html only if it doesn't exist.
+if ! [ -f "${public}/50x.html" ]; then
+    php "${libexec}/50x.php" > "${public}/50x.html" || (
+        echo "Unable to create a 50x.html" >&2;
+        exit 1;
+    )
+fi
diff --git a/tools/bin/manifest b/tools/bin/manifest
--- a/tools/bin/manifest
+++ b/tools/bin/manifest
@@ -34,7 +34,10 @@ then
     )
 fi
 
-php "${libexec}/manifest.php" > "$public/manifest.json" || (
-    echo "Unable to create a manifest.json" >&2;
-    exit 1;
-)
+# Create a menifest.json only if it doesn't exist.
+if ! [ -f "${public}/manifest.json" ]; then
+    php "${libexec}/manifest.php" > "${public}/manifest.json" || (
+        echo "Unable to create a manifest.json" >&2;
+        exit 1;
+    )
+fi
